name: Build Sing-box AAR

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sing-box source
        uses: actions/checkout@v4
        with:
          repository: 'SagerNet/sing-box'
          ref: 'v1.9.3'
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # 救命关键步：强制让服务器现场下载缺失的 NDK！
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Build Android AAR
        run: |
          # 把刚刚下载好的 NDK 喂给它！
          export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          export PATH="$PATH:$(go env GOPATH)/bin"
          
          make lib_install
          make lib_android

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libbox-aar
          path: ./*.aar
