name: Build Sing-box AAR

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04  # 核心秘诀1：强行降级使用稳定的老版服务器系统
    steps:
      - name: Checkout sing-box source
        uses: actions/checkout@v4
        with:
          repository: 'SagerNet/sing-box'
          ref: 'v1.9.3'
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c  # 核心秘诀2：让系统现场强行下载并安装 NDK！

      - name: Build Android AAR
        run: |
          # 核心秘诀3：把刚刚下载好的 NDK 路径直接塞进环境变量！
          export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          export PATH="$PATH:$(go env GOPATH)/bin"
          
          make lib_install
          make lib_android

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libbox-aar
          path: ./*.aar
